name             'grafter'
maintainer       'Jeffrey Peckham'
maintainer_email 'abic@ophymx.com'
license          'Apache 2.0'
version          '0.0.1'

supports 'ubuntu'
supports 'redhat'
supports 'debian'
supports 'centos'
supports 'fedora'
